### ISSUE TITLE
Null object on setBackground

### ISSUE THREAD

**Issue by whywilson** [GrenderG/Toasty#147]
Always get force close.
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackground(android.graphics.drawable.Drawable)' on a null object reference
        at es.dmoral.toasty.ToastyUtils.setBackground(ToastyUtils.java:49)
        at es.dmoral.toasty.Toasty.custom(Toasty.java:316)
        at es.dmoral.toasty.Toasty.error(Toasty.java:242)
        at es.dmoral.toasty.Toasty.error(Toasty.java:220)

Please help to solve the issues. Thank you for the work.

**Comment by alishe79** [comment]
hi.
if you have a toast_layout.xml file in layouts resource directorty, delete or rename it.
have a good programming.
