### ISSUE TITLE
atal Exception: android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by arunsaini065** [GrenderG/Toasty#175]
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f080367
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
       at android.content.res.Resources.getDrawable(Resources.java:819)
       at android.content.Context.getDrawable(Context.java:618)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:864)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:483)
       at es.dmoral.toasty.ToastyUtils.getDrawable(ToastyUtils.java:54)
       at es.dmoral.toasty.ToastyUtils.tint9PatchDrawableFrame(ToastyUtils.java:42)
       at es.dmoral.toasty.Toasty.custom(Toasty.java:305)
       at es.dmoral.toasty.Toasty.normal(Toasty.java:106)
       at es.dmoral.toasty.Toasty.normal(Toasty.java:81)
       at com.rocks.photosgallery.newui.NewUIHomeScreen.onBackPressed(NewUIHomeScreen.java:342)
       at android.app.Activity.onKeyUp(Activity.java:2980)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2858)
       at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:354)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4801)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4673)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4215)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4268)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4234)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4361)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4242)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4418)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4215)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4268)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4234)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4242)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4215)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4268)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4234)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4394)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4555)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2448)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2011)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2002)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2425)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by harmeetsingh-work** [comment]
Try this: https://github.com/GrenderG/Toasty/issues/84#issuecomment-1192902092
