### ISSUE TITLE
 java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by hnyer** [GrenderG/Toasty#27]
java.lang.NoSuchFieldError: No static field toast_icon of type I in class Les/dmoral/toasty/R$id; or its superclasses (declaration of 'es.dmoral.toasty.R$id' appears in

**Comment by GrenderG** [comment]
Please, provide more info about what have you done in order to get that error. I think you have also a resource / field called `toast_icon` and it's causing conflicts with Toasty's ImageView with the same name.

**Comment by GrenderG** [comment]
Gonna close this as no feedback has been given.

**Comment by chenfd99** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.dreamtd.tapplay, PID: 31128
                                                                     java.lang.NoSuchFieldError: No static field toast_icon of type I in class Les/dmoral/toasty/R$id; or its superclasses (declaration of 'es.dmoral.toasty.R$id' appears in /data/app/com.dreamtd.tapplay-1/base.apk:classes22.dex)
                                                                         at es.dmoral.toasty.Toasty.custom(Toasty.java:174)
                                                                         at es.dmoral.toasty.Toasty.info(Toasty.java:116)
                                                                         at es.dmoral.toasty.Toasty.info(Toasty.java:106)
                                                                         at com.dreamtd.tapplay_new.dialog.FunnyVoiceDialog.playVoice(FunnyVoiceDialog.kt:108)
                                                                         at com.dreamtd.tapplay_new.dialog.FunnyVoiceDialog.access$playVoice(FunnyVoiceDialog.kt:28)
                                                                         at com.dreamtd.tapplay_new.dialog.FunnyVoiceDialog$initViews$3.doResume(FunnyVoiceDialog.kt:56)
                                                                         at com.dreamtd.tapplay_new.dialog.FunnyVoiceDialog$initViews$3.invoke(FunnyVoiceDialog.kt)
                                                                         at com.dreamtd.tapplay_new.dialog.FunnyVoiceDialog$initViews$3.invoke(FunnyVoiceDialog.kt:28)
                                                                         at org.jetbrains.anko.sdk25.coroutines.Sdk25CoroutinesListenersWithCoroutinesKt$onClick$1$1.doResume(ListenersWithCoroutines.kt:285)
                                                                         at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                         at kotlinx.coroutines.experimental.DispatchedContinuation$resume$1.run(CoroutineDispatcher.kt:171)
                                                                         at android.os.Handler.handleCallback(Handler.java:742)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5523)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by chenfd99** [comment]
Toasty.info(context, player!!.isPlaying.toString()).show()

**Comment by GrenderG** [comment]
@chenfd99 As I said that problem will happen whenever in one application has two files with the same name in two different modules.
