### ISSUE TITLE
java.lang.NoSuchFieldError: No static field toast_icon of type I in class Les/dmoral/toasty/R$id; or its superclasses (declaration of 'es.dmoral.toasty.R$id' appears in /data/app/com.***

### ISSUE THREAD

**Issue by chenfd99** [GrenderG/Toasty#52]
as 3.0.1
build.gradle
`
compileSdkVersion 26
buildToolsVersion "26.0.3"
minSdkVersion 16
targetSdkVersion 26
compile 'com.github.GrenderG:Toasty:1.2.8'
`

Activity
`Toasty.success(applicationContext, "sss").show()`

error msg
`01-03 16:47:27.553 26958-26958/com.dreamtd.tapplay E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.dreamtd.tapplay, PID: 26958
                                                                     java.lang.NoSuchFieldError: No static field toast_icon of type I in class Les/dmoral/toasty/R$id; or its superclasses (declaration of 'es.dmoral.toasty.R$id' appears in /data/app/com.dreamtd.tapplay-2/base.apk:classes22.dex)
                                                                         at es.dmoral.toasty.Toasty.custom(Toasty.java:174)
                                                                         at es.dmoral.toasty.Toasty.success(Toasty.java:132)
                                                                         at es.dmoral.toasty.Toasty.success(Toasty.java:122)
                                                                        `

**Comment by LittleSmileMonkey** [comment]
Toasty version 1.2.5
Kotlin version 1.1.51

when i use  `Toasty.error(mContext, msg, Toast.LENGTH_SHORT, withIcon).show();` 

logcat output this error msg

`java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6337)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.NoSuchFieldError: No field toast_icon of type I in class Les/dmoral/toasty/R$id; or its superclasses (declaration of 'es.dmoral.toasty.R$id' appears in /data/app/com.zjjyb.uulicai-2/base.apk:classes26.dex)
	at es.dmoral.toasty.Toasty.custom(Toasty.java:169)
	at es.dmoral.toasty.Toasty.error(Toasty.java:144)
	at com.sleep.commonlib.util.ToastUtil.showErrorToast(ToastUtil.java:91)
	at com.sleep.uulib.netWork.NetCommonMethod.judgeError(NetCommonMethod.kt:33)
	at com.sleep.uulib.netWork.BaseObserver.onError(BaseObserver.kt:25)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:274)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:171)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:250)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	... 7 more
`

**Comment by GrenderG** [comment]
[Answered here.](https://github.com/GrenderG/Toasty/issues/27)

**Comment by chenfd99** [comment]
I found this error  ,   my moudle has a layout named toast_layout.xml   so , I renamed my layout.   and the error was gone
